name: 'Wait for Green'
description: 'Wait for commit statuses and checks to become green'
author: 'Jeff Chen'
inputs:
  token:
    required: true
    description: 'Likely ${{ secrets.GITHUB_TOKEN }}'
outputs:
  success:
    description: '"true" if all statuses are successful or skipped and "false" otherwise'
runs:
  using: 'node16'
  main: 'dist/index.js'
